name: Stop EC2 Server at 9 pm

on:
  schedule:
    - cron: "30 15 * * *"  # Runs at 15:30 UTC (9:00 PM IST)
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  stop-server:
    runs-on: ubuntu-latest

    steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: my-github-actions-session
          aws-region: ${{ secrets.AWS_REGION }}
          
     - name: Check EC2 Instance State
       id: check-state
       run: |
          STATE=$(aws ec2 describe-instances --instance-ids ${{ secrets.INSTANCE_ID }} \
          --query "Reservations[*].Instances[*].State.Name" --output text)
          echo "INSTANCE_STATE=$STATE" >> $GITHUB_ENV
          echo "EC2 Instance is currently: $STATE"

     - name: Stop EC2 Instance if running
       if: env.INSTANCE_STATE == 'running'
       run: |
          aws ec2 stop-instances --instance-ids ${{ secrets.INSTANCE_ID }}
          echo "EC2 Instance stopping"